volumes:
    mysql_data:
networks:
    project_management:
        driver: bridge

services:
    database:
        image: mysql:8.0
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=${DB_DATABASE:-helper}
            - MYSQL_USER=${DB_USERNAME:-helper}
            - MYSQL_PASSWORD=${DB_PASSWORD:-helper}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-helper}
        command: --default-storage-engine innodb
        restart: unless-stopped
        networks:
            - project_management
        healthcheck:
            test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
            interval: 20s
            start_period: 10s
            timeout: 10s
            retries: 3

    app:
        build: .
        environment:
            - APP_URL=${APP_URL:-http://localhost}
            - DB_CONNECTION=${DB_CONNECTION:-mysql}
            - DB_HOST=${DB_HOST:-database}
            - DB_PORT=${DB_PORT:-3306}
            - DB_DATABASE=${DB_DATABASE:-helper}
            - DB_USERNAME=${DB_USERNAME:-helper}
            - DB_PASSWORD=${DB_PASSWORD:-helper}
            - MAIL_MAILER=${MAIL_MAILER:-smtp}
            - MAIL_HOST=${MAIL_HOST:-smtp.mailtrap.io}
            - MAIL_PORT=${MAIL_PORT:-465}
            - MAIL_USERNAME=${MAIL_USERNAME:-username}
            - MAIL_PASSWORD=${MAIL_PASSWORD:-password}
            - MAIL_ENCRYPTION=${MAIL_ENCRYPTION:-tls}
        depends_on:
            - database
        restart: unless-stopped
        # command: /bin/bash -c "./run.sh"
        ports:
            - 8000:8000
        networks:
            - project_management
        volumes:
            - /etc/localtime:/etc/localtime
            - ./supervisor.conf:/etc/supervisor/conf.d/supervisor.conf

    mailpit:
        image: axllent/mailpit
        ports:
            - "${MAILPIT_HTTP_PORT}:8025"
            - "${MAILPIT_SMTP_PORT}:1025"
        networks:
            - project_management
